# Generated by Django 2.0.5 on 2018-05-20 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('researcher_file', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Area')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Area')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(db_index=True)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=200, unique=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Conference')),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('pid', models.CharField(max_length=200, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='researchers',
            field=models.ManyToManyField(to='rest_api.Researcher'),
        ),
        migrations.AddField(
            model_name='department',
            name='areas',
            field=models.ManyToManyField(through='rest_api.DepartmentScore', to='rest_api.Area'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentscore',
            unique_together={('area', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='conference',
            unique_together={('area', 'name')},
        ),
    ]
